apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-deploy-jpet
spec:
  workspaces:
    - name: jpet-workspace
  params:
  - name: git-url
    type: string
    description: url of the git repo for the code of deployment
    default: "https://github.com/jmlafont/jpetstore-kubernetes.git"
  - name: git-revision
    type: string
    description: revision to be used from repo of the code for deployment
    default: "master"
  - name: password
    description: password docker

  tasks:
  - name: clone-repository
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: jpet-workspace
    params:
    - name: url
      value: $(params.git-url)
    - name: deleteExisting
      value: "true"
    - name: revision
      value: $(params.git-revision)

  - name: build-jpet-web
    taskRef:
      name: buildah
      kind: ClusterTask
    workspaces:
      - name: source
        workspace: jpet-workspace
    params:
      - name: DOCKERFILE 
        value: './jpetstore/Dockerfile'
      - name: TLSVERIFY
        value: "false"
      - name: IMAGE
        value: quay.io/jmlafont/jpetstore-web
      - name: CONTEXT
        value: jpetstore
      - name: PUSH_EXTRA_ARGS
        value: "--creds jmlafont:$(params.password)"
    runafter:
      - clone-repository

  - name: build-jpet-db
    taskRef:
      name: buildah
      kind: ClusterTask
    workspaces:
      - name: source
        workspace: jpet-workspace
    params:
      - name: DOCKERFILE 
        value: './jpetstore/db/Dockerfile'
      - name: TLSVERIFY
        value: "false"
      - name: IMAGE
        value: quay.io/jmlafont/jpetstore-db
      - name: CONTEXT
        value: jpetstore
      - name: PUSH_EXTRA_ARGS
        value: "--creds jmlafont:$(params.password)"
    runafter:
      - clone-repository

  - name: deploy-jpet
    taskRef:
      name: deploy-jpet
    workspaces:
      - name: source
        workspace: jpet-workspace
    runafter:
      - build-jpet-web

---

apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: jpet-git
spec:
  params:
    - name: url
      value: 'https://github.com/jmlafont/jpetstore-kubernetes.git'
  type: git

---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-jpet
spec:
  workspaces:
    - name: source  
  steps:
    - name: deploy
      image: quay.io/openshift/origin-cli:latest
      workingDir: /workspace/source/YAML
      command: ["/bin/bash", "-c"]
      args:
        - |-
          echo "**** Deploy manifest ****"
          oc apply -f jpetstore.yaml

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jpet-workspace
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-ceph-cephfs-internal

