apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: jpetstore
  namespace: jpetstore-project
  labels:
    app: jpetstore
spec:
  componentKinds:
  - group: app.ibm.com
    kind: Subscription
