apiVersion: app.ibm.com/v1alpha1
kind: PlacementRule
metadata:
  name: jpetstore-placement-db
  namespace: jpetstore-project
  labels:
    app: jpetstore
    release: jpetstore-devchan
spec:
  clusterReplicas: 1
  clusterLabels:
    matchLabels:
      environment: Dev
