- name: deploy JPET war
  hosts: web_servers
  vars:
    war_file: jpetstore.war
    http_port: 8086
    https_port: 8444
    admin_username: demo
    admin_password: demo
  roles:
    - mysql-install
    - tomcat-install

  tasks:

    - name: copy WAR  
      copy:
        src: "{{war_file}}"
        dest: "/usr/share/tomcat/webapps/{{war_file}}"

    - name: copy initdb files
      copy:
        src: "../jpetstore/db/mysql5/{{item}}"
        dest: "{{item}}" 
      loop: 
        - jpetstore-mysql-1-schema.sql
        - jpetstore-mysql-2-dataload.sql

    - name: init db
      shell: mysql -u jpetstore -pjppwd jpetstore <  jpetstore-mysql-1-schema.sql

    - name: init db data
      shell: mysql -u jpetstore -pjppwd jpetstore <  jpetstore-mysql-2-dataload.sql

    - name: copy jdbc lib
      copy:
        src: "../jpetstore/lib/mysql-connector-java-3.0.17-ga-bin.jar"
        dest: "/usr/share/tomcat/webapps/jpetstore/WEB-INF/lib/"
#
#    - name: configure DB connexion
#      debug:
#        msg: "configure DB connexion NON IMPLEMENTE" 
